import { Command,  prompt,
  commander, PinionContext, renderTemplate, toFile } from '@featherscloud/pinion'
import { Eta } from "eta"

// A Context interface. (This one is empty)
interface Context extends PinionContext {
  name: string
  description: string
  ch: string[]
}

// The file content as a template string
function readmeEta(ctx:Context) {
  const eta = new Eta({ views: __dirname });
  const res = eta.render("./tpl/hello.eta",ctx);
  return res;
}
function readme(ctx:Context) {
  console.log(ctx)
  return `# Hello world
  ${ctx.name}
This is a readme generated by Pinion
Copyright (c) ${new Date().getFullYear()}
`
}


const program = new Command()
  .description('A readme generator')
  .option('-n, --name <name>', 'Name of your app')
  .option('-d, --description <description>', 'The description for your app')
  .option('-c, --ch [ch...]', 'ch')

// A `generate` export that wraps the context and renders the template
export async function  generate(init: Context) {
  return Promise.resolve(init)
  .then(commander(program))
  .then(
    prompt((context) => {
      // Only ask question if `name` or `description` are not passed
      return {
        name: {
          type: 'input',
          message: 'What is the name of your app?',
          when: !context.name
        },
        description: {
          type: 'input',
          message: 'Write a short description',
          when: !context.description
        },
        chs: {
          type: 'checkbox',
          message: 'Select a package manager',
          choices: [
            { name: 'npm', value: 'npm' },
            { name: 'yarn', value: 'yarn' },
            { name: 'pnpm', value: 'pnpm', disabled: true },
            {
              name: 'pnpm',
              value: 'pnpm',
            },
          ],
          when: !context.ch
        }
      }
    })
  )
  .then(renderTemplate(readmeEta, toFile('readmeEta.md')))
  .then(renderTemplate(readme, toFile('readme.md')))
}